[package]
name = "url2ref"
version = "0.1.0"
edition = "2021"
default-run = "rocket_app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
tera = "1.19.1"
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
grass = "0.13.1"