name: build_and_test

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Rust toolchain
      uses: hecrj/setup-rust-action@v2.0.0
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install npm dependencies
      working-directory: ./npm
      shell: bash
      run: ./build.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: cargo test --verbose
