name: build_and_test

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Rust toolchain
      uses: hecrj/setup-rust-action@v2.0.0
      with:
        rust-version: nightly
    - name: Install npm dependencies
      working-directory: ./npm
      run: |
        npm install
        npm run build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
